### ISSUE TITLE
Window flashes white on launch on Windows

### ISSUE THREAD

**Issue by zeozeozeo** [emilk/egui#3625]
**Describe the bug**
This was previously fixed in https://github.com/emilk/egui/issues/1802, but was reintroduced in commit https://github.com/emilk/egui/commit/1571027556b57cef5908df094038795c09b9090a.

**To Reproduce**
1. Start app in debug or release mode
2. Window flashes white for ~0.5 seconds

**Expected behavior**
No window flash on startup.

**Screenshots**
![window-flash](https://github.com/emilk/egui/assets/108888572/31a675af-8c30-46b1-a1af-653491cf67da)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.24.0

**Additional context**
Perhaps the `is_first_frame` check is broken, or the window is being created with `set_visible(true)` in the first place, when it should start invisible until all assets are loaded.

**Comment by 7sDream** [comment]
Can reproduce this after upgrade to 0.24.0. 

OS: Windows 11 Preview Build 25997

**Comment by zeozeozeo** [comment]
Fixed in https://github.com/emilk/egui/pull/3631.

**Comment by sourcebox** [comment]
I also had this issue on macOS, did not do extensive testing though.

**Comment by MrWheatley** [comment]
The white flashing is still happening to me with 0.25.0 and on master as well.

![gif](https://github.com/emilk/egui/assets/28412095/363ae6d9-4ace-4206-ad1a-3acbfa83101a)

**Comment by emilk** [comment]
Is both the `glow` and `wgpu` backends affected?

**Comment by MrWheatley** [comment]
Trying to use the `wgpu` backend I get this error:
```sh
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.18.0`
    ... which satisfies dependency `wgpu = "^0.18.0"` of package `eframe v0.25.0 (https://github.com/emilk/egui.git?branch=master#7733d1d8)`
    ... which satisfies git dependency `eframe` of package `temp v0.1.0 (C:\Users\mrmon\PycharmProjects\temp)`
versions that meet the requirements `^0.3.64` (locked to 0.3.67) are: 0.3.67

the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.


failed to select a version for `web-sys` which could resolve this conflict
```

**Comment by torokati44** [comment]
meta: This issue is currently "left behind" in the "0.24.1" milestone. Shouldn't it be moved into the rolling "Next Major Release" one now?

**Comment by emilk** [comment]
@torokati44 good catch!

**Comment by zeozeozeo** [comment]
> The white flashing is still happening to me with 0.25.0 and on master as well.
> 
> ![gif](https://github.com/emilk/egui/assets/28412095/363ae6d9-4ace-4206-ad1a-3acbfa83101a)
> 

Can't replicate this on Windows, and the window flash on your example does seem much shorter. Are you on X11/Wayland?

**Comment by MrWheatley** [comment]
I'm on Windows 10. The flashes are very inconsistent for me. Sometimes they're long, sometimes they're short, and sometimes there are no flashes at all.

**Comment by sodamouse** [comment]
I face this issue on egui = "0.31.1" if the window is set to be maximized by default. Is there a way to avoid showing the window until the first frame is drawn?

**Comment by zeozeozeo** [comment]
> I face this issue on egui = "0.31.1" if the window is set to be maximized by default. Is there a way to avoid showing the window until the first frame is drawn?

I can reproduce this on master, @sodamouse can you open an issue for it?
seems that windows just doesn't respect the window being invisible if it's maximized
